# Generated by Django 3.2.8 on 2021-11-06 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0018_auto_20211103_2237'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Specialist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Category', models.CharField(blank=True, choices=[('Pre-Sale Question', 'Pre-Sale Question'), ('Order Question', 'Order Question'), ('Return', 'Return'), ('Shipping', 'Shipping'), ('Product Availability', 'Product Availability'), ('Plant caring', 'Plant caring'), ('General', 'General')], default='General', max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('answer_tickect', models.ManyToManyField(blank=True, related_name='answer_tickect', to='Ticket.TicketModel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='Users.member')),
                ('question_tickect', models.ManyToManyField(blank=True, related_name='question_tickect', to='Ticket.TicketModel')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='Specialist.specialist')),
            ],
        ),
    ]
