# Generated by Django 3.2.8 on 2021-12-26 07:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist', '0001_initial'),
        ('Users', '0024_auto_20211216_2000'),
        ('Ticket', '0002_alter_ticketmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Category', models.CharField(blank=True, choices=[('Pre-Sale Question', 'Pre-Sale Question'), ('Order Question', 'Order Question'), ('Return', 'Return'), ('Shipping', 'Shipping'), ('Product Availability', 'Product Availability'), ('Plant caring', 'Plant caring'), ('General', 'General')], default='General', max_length=50, null=True)),
                ('ticket_status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('In progress', 'In progress'), ('Accepted', 'Accepted'), ('Done', 'Done')], default='Sent', max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('ticket_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_author', to='Users.member')),
                ('ticket_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_specialist', to='Specialist.specialist')),
            ],
        ),
    ]
