# Generated by Django 3.2.8 on 2021-10-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_tag_usage'),
        ('Cart', '0002_auto_20211024_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcartmodel',
            name='plant_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.plant'),
        ),
        migrations.AlterField(
            model_name='toolcartmodel',
            name='tool_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.tool'),
        ),
    ]
