# Generated by Django 3.2.8 on 2021-10-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20211020_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SPECIALIST', 'Specialist'), ('MEMBER', 'Member')], max_length=50, verbose_name='type'),
        ),
    ]
