# Generated by Django 3.2.8 on 2021-10-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_tag_usage'),
        ('Users', '0008_alter_memberfields_plants_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfields',
            name='plants_cart',
            field=models.ManyToManyField(blank=True, to='Backend.Plant'),
        ),
    ]
