# Generated by Django 3.2.8 on 2021-11-02 07:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20211102_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specilistfields',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+## ### ### ####'. Up to 10 digits allowed.", regex='^(\\+\\d{1,2}\\s?)?1?\\-?\\.?\\s?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')], verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='specilistfields',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_user', to='Users.specialist'),
        ),
    ]
