# Generated by Django 3.2.8 on 2021-11-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_alter_newuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='calnderID',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
