# Generated by Django 3.2.8 on 2021-11-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_auto_20211128_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='calnderID',
            new_name='calendarID',
        ),
    ]
