# Generated by Django 3.2.8 on 2021-12-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_rename_calnderid_newuser_calendarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='calendarID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='creds',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
