# Generated by Django 3.2.8 on 2021-10-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.album'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_images', to='Backend.album'),
        ),
    ]
