# Generated by Django 3.2.8 on 2021-10-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_auto_20211027_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.album'),
        ),
    ]
