# Generated by Django 3.2.8 on 2021-11-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='kind',
            field=models.CharField(blank=True, default='Plant', max_length=10),
        ),
    ]
