# Generated by Django 4.2 on 2023-04-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
