# Generated by Django 4.2 on 2023-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_plant_main_image_alter_tool_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='main_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='main_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
