# Generated by Django 4.2 on 2023-04-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_toolcomment_plantcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.plantcomment'),
        ),
        migrations.AlterField(
            model_name='toolcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.toolcomment'),
        ),
    ]
