# Generated by Django 4.2 on 2023-04-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_plant_main_image_alter_tool_main_image'),
        ('store', '0003_alter_plantcomment_reply_to_and_more'),
    ]

    operations = [
    ]
