# Generated by Django 4.2 on 2023-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_seller'),
        ('store', '0004_merge_20230422_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='seller',
            field=models.ManyToManyField(to='user.seller'),
        ),
        migrations.AddField(
            model_name='tool',
            name='seller',
            field=models.ManyToManyField(to='user.seller'),
        ),
    ]
