version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - talebi-db-data:/var/lib/postgresql/data
    env_file:
      - ".env"

  redis:
    image: redis:7.2-rc2-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  backend:
    depends_on:
      - db
    build: ./
    ports:
      - "443:80"
      - "80:80"
    volumes:
      - .:/usr/src/app
    command: sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:80"
    env_file:
      - ".env"

volumes:
  talebi-db-data:
  redis-data:
