# Generated by Django 3.2.8 on 2021-11-10 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Green_House', '0006_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='locations',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='myplant',
            name='location',
        ),
        migrations.AddField(
            model_name='myplant',
            name='locations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)}, to='Green_House.location'),
        ),
    ]
