# Generated by Django 4.2.1 on 2023-07-07 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_merge_20230422_0746'),
        ('common', '0003_toolbookmark_plantbookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantbookmark',
            unique_together={('user', 'Plant')},
        ),
        migrations.AlterUniqueTogether(
            name='toolbookmark',
            unique_together={('user', 'Tool')},
        ),
    ]
