# Generated by Django 3.2.8 on 2021-11-09 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0004_auto_20211024_1524'),
        ('Backend', '0016_alter_image_name'),
        ('Green_House', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.ManyToManyField(blank=True, to='Green_House.Location')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='myPlants',
        ),
    ]
