# Generated by Django 4.2.1 on 2023-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_house', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='location',
        ),
        migrations.AddField(
            model_name='userplant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
