# Generated by Django 4.2.1 on 2023-05-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_house', '0003_remove_userplant_image_remove_userplant_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplant',
            name='is_archived',
        ),
    ]
