# Generated by Django 4.2.1 on 2023-07-07 07:40

from django.db import migrations, models
import green_house.models


class Migration(migrations.Migration):

    dependencies = [
        ('green_house', '0004_remove_userplant_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=green_house.models.upload_to),
        ),
    ]
