# Generated by Django 3.2.8 on 2021-11-10 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Green_House', '0004_auto_20211109_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myplant',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myplant',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
