# Generated by Django 3.2.8 on 2021-11-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Green_House', '0007_auto_20211110_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myplant',
            name='locations',
        ),
        migrations.AddField(
            model_name='myplant',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
