# Generated by Django 3.2.8 on 2021-10-19 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('water', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('much', 'much')], max_length=50)),
                ('light', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('much', 'much')], max_length=50)),
            ],
        ),
    ]
