# Generated by Django 3.2.8 on 2021-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20211019_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='environment',
            field=models.CharField(blank=True, choices=[('tropical', 'tropical'), ('cold', 'cold'), ('none', 'none')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
