# Generated by Django 3.2.8 on 2021-10-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20211019_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='growthRate',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('much', 'much')], max_length=50, null=True),
        ),
    ]
