# Generated by Django 3.2.8 on 2021-10-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20211023_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='usage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
