# Generated by Django 3.2.8 on 2021-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_alter_plant_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='kind',
            field=models.CharField(blank=True, default='Tool', editable=False, max_length=10),
        ),
    ]
