# Generated by Django 3.2.8 on 2022-01-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specilistfields',
            name='major',
            field=models.CharField(blank=True, max_length=150, verbose_name='major'),
        ),
    ]
