# Generated by Django 4.1.7 on 2023-04-07 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantcart',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.plant'),
        ),
        migrations.AddField(
            model_name='plantcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='toolcart',
            unique_together={('user', 'tool')},
        ),
        migrations.AlterUniqueTogether(
            name='plantcart',
            unique_together={('user', 'plant')},
        ),
    ]
