# Generated by Django 3.2.8 on 2021-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_tool_image'),
        ('Users', '0004_alter_newuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfields',
            name='plants_cart',
            field=models.ManyToManyField(blank=True, to='Backend.Plant'),
        ),
        migrations.AddField(
            model_name='memberfields',
            name='tools_cart',
            field=models.ManyToManyField(blank=True, to='Backend.Tool'),
        ),
    ]
