# Generated by Django 3.2.8 on 2021-10-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_tool_image'),
        ('Users', '0005_auto_20211022_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfields',
            name='credit_value',
            field=models.IntegerField(default=0, verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='memberfields',
            name='plants_cart',
            field=models.ManyToManyField(blank=True, to='Backend.Plant'),
        ),
        migrations.AlterField(
            model_name='memberfields',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
