# Generated by Django 3.2.8 on 2021-10-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20211023_2143'),
        ('Users', '0006_auto_20211023_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfields',
            name='plants_cart',
            field=models.ManyToManyField(blank=True, to='Backend.Plant'),
        ),
    ]
