# Generated by Django 3.2.8 on 2021-11-02 07:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_memberfields_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='specilistfields',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='specilistfields',
            name='address',
            field=models.TextField(blank=True, max_length=500, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='specilistfields',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
        migrations.AddField(
            model_name='specilistfields',
            name='degree',
            field=models.CharField(choices=[('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctoral', 'Doctoral')], max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='specilistfields',
            name='id_code',
            field=models.CharField(blank=True, max_length=150, verbose_name='id_code'),
        ),
        migrations.AddField(
            model_name='specilistfields',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specilistfields',
            name='major',
            field=models.CharField(blank=True, max_length=150, verbose_name='id_code'),
        ),
        migrations.AddField(
            model_name='specilistfields',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+## ### ### ####'. Up to 10 digits allowed.", regex='^(\\+\\d{1,2}\\s?)?1?\\-?\\.?\\s?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='specilistfields',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='specilistfields',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
