# Generated by Django 3.2.8 on 2021-11-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20211102_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specilistfields',
            name='degree',
            field=models.CharField(blank=True, choices=[('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctoral', 'Doctoral')], max_length=50, null=True, verbose_name='degree'),
        ),
    ]
