# Generated by Django 3.2.8 on 2021-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_auto_20211103_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SPECIALIST', 'Specialist'), ('MEMBER', 'Member')], default='MEMBER', max_length=50, verbose_name='type'),
        ),
    ]
