# Generated by Django 3.2.8 on 2021-11-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_newuser_calnderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='creds',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
