# Generated by Django 3.2.8 on 2021-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_newuser_creds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='calnderID',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='creds',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
