# Generated by Django 4.2.1 on 2023-05-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Non-Binary'), (3, 'Rather not to say!')], default=3, null=True),
        ),
    ]
