# Generated by Django 4.2.1 on 2023-06-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_specialist'),
        ('user', '0002_user_gender'),
    ]

    operations = [
    ]
