# Generated by Django 4.2 on 2023-05-05 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rate',
            field=models.FloatField(help_text='enter integer between 1 and 5!', validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
