# Generated by Django 4.2.1 on 2023-07-05 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(regex='^(\\\\+98|0)?9\\\\d{9}$')]),
        ),
    ]
