# Generated by Django 3.2.8 on 2021-11-19 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0019_alter_newuser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastWateringLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.member')),
            ],
        ),
        migrations.CreateModel(
            name='LastSeenLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.member')),
            ],
        ),
        migrations.CreateModel(
            name='CoinManagementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coin_vlaue', models.IntegerField(default=200, verbose_name='coin_value')),
                ('used_plant_count', models.IntegerField(blank=True, default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.member')),
            ],
        ),
    ]
