# Generated by Django 3.2.8 on 2021-12-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_rename_calnderid_newuser_calendarid'),
        ('Coin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinmanagementmodel',
            old_name='coin_vlaue',
            new_name='coin_value',
        ),
        migrations.AlterField(
            model_name='coinmanagementmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.member'),
        ),
        migrations.AlterField(
            model_name='lastseenlogmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.member'),
        ),
        migrations.AlterField(
            model_name='lastwateringlogmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.member'),
        ),
    ]
