# Generated by Django 4.1.7 on 2023-03-09 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Category', models.CharField(blank=True, choices=[('Pre-Sale Question', 'Pre-Sale Question'), ('Order Question', 'Order Question'), ('Return', 'Return'), ('Shipping', 'Shipping'), ('Product Availability', 'Product Availability'), ('Plant caring', 'Plant caring'), ('General', 'General')], default='General', max_length=50, null=True)),
                ('ticket_status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('In progress', 'In progress'), ('Accepted', 'Accepted'), ('Done', 'Done')], default='Sent', max_length=50, null=True)),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Category', models.CharField(blank=True, choices=[('Pre-Sale Question', 'Pre-Sale Question'), ('Order Question', 'Order Question'), ('Return', 'Return'), ('Shipping', 'Shipping'), ('Product Availability', 'Product Availability'), ('Plant caring', 'Plant caring'), ('General', 'General')], default='General', max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
