# Generated by Django 3.2.8 on 2021-12-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_supportticketmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketmodel',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='supportticketmodel',
            name='body',
            field=models.TextField(),
        ),
    ]
