# Generated by Django 4.2.1 on 2023-07-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('order', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plant_cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tool_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='plants',
            field=models.ManyToManyField(to='cart.plantcart'),
        ),
        migrations.AddField(
            model_name='order',
            name='tools',
            field=models.ManyToManyField(to='cart.toolcart'),
        ),
    ]
