# Generated by Django 4.2.1 on 2023-07-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_plant_cart_remove_order_tool_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_after',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_before',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
