# Generated by Django 4.2.1 on 2023-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('order', '0005_order_price_after_order_price_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plants',
            field=models.ManyToManyField(blank=True, null=True, to='cart.plantcart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='cart.toolcart'),
        ),
    ]
