name: service CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-service:
    name: build service image
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set ip docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/talebi-service:lastest

  deploy-service:
    name: deploy service
    runs-on: ubuntu-latest
    needs: build-service
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            docker compose down
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
            cp .env.sample .env
            docker compose -f server-deploy.yml build
            docker compose -f server-deploy.yml up db redis -d
            ./wait-for-it.sh localhost:5432
            docker compose -f server-deploy.yml run --rm backend python3 manage.py migrate
            docker compose -f server-deploy.yml up backend -d

      - name: cleanup
        run: rm -rf ~/.ssh
